# fly.toml app configuration file generated for thea on 2023-06-30T00:19:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thea"
primary_region = "bos"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
